work_dir: ./newwork_dir/ntu60/xsub/SSGCN_joint_21

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: ../CTR-GCN-main/data/ntu/NTU60_CS.npz
  split: train
  window_size: 256
  p_interval: [0.5, 1]
  vel: False
  bone: False
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  normalization: False
  random_rot: True

test_feeder_args:
  data_path: ../CTR-GCN-main/data/ntu/NTU60_CS.npz
  split: test
  window_size: 256
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ssgcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    com: 2
  drop_path: 0.4

batch_size: 64
test_batch_size: 64
device: [1]
nesterov: True
